AarhusWebDevCoop/ViewModels/ContactForm.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;


namespace AarhusWebDevCoop.ViewModels
{
    public class ContactForm
    {
        [Required(ErrorMessage = "Please enter your name")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Please enter your email")]
        [Display(Name = "Email")]
        [RegularExpression(@"^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$",
        ErrorMessage = "Please enter a correct email address")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Please enter a subject")]
        public string Subject { get; set; }

        [Required(ErrorMessage = "Please enter a message")]
        public string Message { get; set; }
    }
}

AarhusWebDevCoop/Controllers/ContactFormSurfaceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.Mvc;
using AarhusWebDevCoop.ViewModels;
using System.Net.Mail;
using Umbraco.Core.Models;

namespace AarhusWebDevCoop.Controllers
{
    public class ContactFormSurfaceController : SurfaceController
    {
        // GET: ContactFormSurface
        public ActionResult Index()
        {
            return PartialView("ContactForm", new ContactForm());
        }

        [HttpPost]
        public ActionResult HandleFormSubmit(ContactForm model)
        {
            if (!ModelState.IsValid) { return CurrentUmbracoPage(); }
            TempData["success"] = true;

            MailMessage message = new MailMessage();
            message.To.Add("username@eaaa.dk");
            message.Subject = model.Subject;
            message.From = new MailAddress(model.Email, model.Name);
            message.Body = model.Message;

            IContent msg = Services.ContentService.CreateContent(model.Subject, CurrentPage.Id, "message");
            msg.SetValue("messageName", model.Name);
            msg.SetValue("email", model.Email);
            msg.SetValue("subject", model.Subject);
            msg.SetValue("messageContent", model.Message);

            Services.ContentService.Save(msg);

            using (SmtpClient smtp = new SmtpClient())
            {
                smtp.DeliveryMethod = SmtpDeliveryMethod.Network;
                smtp.UseDefaultCredentials = false;
                smtp.EnableSsl = true;
                smtp.Host = "smtp.gmail.com";
                smtp.Port = 587;
                smtp.Credentials = new System.Net.NetworkCredential("laurynasofficial@gmail.com", "skrrrrrrr");
                // send mail
                smtp.Send(message);
            }

            return RedirectToCurrentUmbracoPage();
        }
    }
}

AarhusWebDevCoop/Views/AboutUs.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.AboutUs>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}
@*@Model.GetGridHtml("aboutGrid")*@
<div class="container pt-4 pb-4">
    @Html.GetGridHtml(Umbraco.AssignedContentItem, "aboutGrid", "bootstrap3")
</div>

AarhusWebDevCoop/Views/ArticlesItem.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.ArticlesItem>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}
<div class="container pt-4 pb-4">
    <h1>@Umbraco.Field("articleTitle")</h1>
    @Umbraco.Field("articleContent")
</div>

AarhusWebDevCoop/Views/ArticlesOverview.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.ArticlesOverview>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}

<div class="container pt-4 pb-4">
    <h1>@Umbraco.Field("articleTitle")</h1>
    @Umbraco.RenderMacro("listArticles")
</div>

AarhusWebDevCoop/Views/ContactPage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.ContactPage>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}

<div class="container pt-4 pb-4">
    <h2>@Model.Name</h2>
    @Html.Action("Index", "ContactFormSurface")
</div>

AarhusWebDevCoop/Views/HomePage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.HomePage>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}
<div class="container pt-4 pb-4">
    <h1>Newest Projects</h1>
    @Umbraco.RenderMacro("listNewestProjects")
</div>

AarhusWebDevCoop/Views/Login.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.Login>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}
<div class="content pt-4 pb-4">
 @Html.Partial("loginForm")   
</div>

AarhusWebDevCoop/Views/MacroPartials/listArticles.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@{ 
    var selection = CurrentPage.Children.Where("Visible").OrderBy("CreateDate desc"); 
    @* OrderBy() takes the property to sort by and optionally order desc/asc *@
}

@foreach (var item in selection)
{
      <hr/>  
      <div class="col-sm-6">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title"><div class="articletitle"><a href="@item.Url">@item.articleTitle</a></div></h5>
            <div class="articlepreview">@Umbraco.Truncate(@item.articleContent,100)</div>
            <a class-"btn btn-primary" href="@item.Url">Read More..</a>
          </div>
        </div>
      </div>
}

AarhusWebDevCoop/Views/MacroPartials/listNewestProjects.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage

@{
    var root = Model.Content.Site();
    //var selection = root.Children.Where(x => x.IsVisible()).ToArray();
}

@{
    var selection = root.Children.Where(x => x.DocumentTypeAlias == "projectOverview")
    .First()
    .Children()
    .Where(x => x.HasValue("projectStatus") && Umbraco.GetPreValueAsString(x.GetPropertyValue<int>("projectStatus")) == "Completed")
    .OrderByDescending(p => p.CreateDate)
    .Take(3);
}

    @foreach (var project in selection) {
     <hr />
    <div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">@project.GetPropertyValue("projectTitle")</h5>
   
        <a href="@project.Url">Read more</a>
    </div>
</div>
}

AarhusWebDevCoop/Views/MacroPartials/listProject.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@{ 
    var selection = CurrentPage.Children.Where("Visible").OrderBy("CreateDate desc"); 
    @* OrderBy() takes the property to sort by and optionally order desc/asc *@
}

@foreach (var item in selection)
{
      <hr/>  
      <div class="col-sm-6">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title"><div class="articletitle"><a href="@item.Url">@item.projectTitle</a></div></h5>
            @*<p class="card-text">@item.articleContent</p>*@
            <div class="articlepreview">@Umbraco.Truncate(@item.projectDescription,100)</div>
            <a class-"btn btn-primary" href="@item.Url">Read More..</a>
          </div>
        </div>
      </div>
}

AarhusWebDevCoop/Views/MacroPartials/mainMenu.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@using Umbraco.Web

@{
    // we store ancestor node with a level of one in 'root variable to avoid over-querying
    var root = Model.Content.Site();
    // we store all published nodes in an array
    var selection = root.Children.Where(x => x.IsVisible()).ToArray();
}

<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <!-- menu button for smaller screens -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav mr-auto">
            <!-- check if name of current content equals to the name of root node, if it does we set the CSS class to 'active', otherwise we set it to null-->
            <li class="@((Model.Content.Name == root.Name)? "active": null) nav-item">
                <!-- set href attribute to the url of our root node and sets the text inside the tag to the name of our root node -->
                <a class="nav-link" href="@root.Url">@root.Name</a>

                <!--check if the array is not empty -->
                @if (selection.Length > 0) {
                    <!--loop through each node in the array -->
                    foreach (var item in selection) {
                        <!-- check if node has any children -->
                        if (item.Children().Where(x => x.IsVisible()).Count() > 0) { 
                        <!-- check if name of current content equals to the name of this node, if it does we set the CSS class to 'active', otherwise we set it to null -->
                        <li class="@((item.Name == Model.Content.Name) ? "active" : null) nav-item dropdown">
                            <!-- create a link with dropdown-toggle class, which will be used to display dropdown containing current node's children -->
                            <!-- set href attribute to the url of current node and set the text inside the tag to the name of current node -->
                            <a class="nav-link dropdown-toggle" href="@item.Url" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                @item.Name
                            </a>

                            <!-- div for dropdown menu-->
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <!-- loop through each visible child of current node -->
                                @foreach (var subMenuItem in item.Children().Where(x => x.IsVisible()))
                                {
                                    <!-- check if node with given id and path has public access restrictions and store returned boolean in a variable -->
                                    var isProtected = umbraco.library.IsProtected(subMenuItem.Id, subMenuItem.Path);
                                    
                                    <!-- check if node with given id and path has user access and store returned boolean in a variable -->
                                    var loginAccess = isProtected && umbraco.library.HasAccess(subMenuItem.Id, subMenuItem.Path);

                                    <!-- check if current node is a project -->
                                    if (subMenuItem.DocumentTypeAlias == "projectItem") {
                                        <!-- check if the project status equals to completed-->
                                        if (Umbraco.GetPreValueAsString(subMenuItem.GetPropertyValue<int>("projectStatus")) == "Completed") {
                                            <!-- check if there are no restrictions or if user has access, if so create the submenu links -->
                                            if (!isProtected || loginAccess) {
                                                <a class="dropdown-item " href="@subMenuItem.Url">@subMenuItem.Name</a>
                                            }
                                        } else {
                                            <!-- check if there are no restrictions or if user has access, if so create the submenu links -->                                        
                                            if (!isProtected || loginAccess) {
                                                <a class="dropdown-item " href="@subMenuItem.Url">@subMenuItem.Name</a>
                                            }
                                        }
                                        
                                    } else { <!-- if we reach this point then the node is an article, so we display it normally -->
                                        if (!isProtected || loginAccess) {
                                            <a class="dropdown-item " href="@subMenuItem.Url">@subMenuItem.Name</a>
                                        }
                                    }
                                }

                            </div>
                        </li>
                    } else { <!-- if we reach this points, it means that node doesn't have any children, so we display it normally, without the dropdown -->
                        <li class="nav-item @(item.IsAncestorOrSelf(Model.Content) ? "active" : null)">
                            <a class="nav-link" href="@item.Url">@item.Name</a>
                        </li>
                    }
                }
            }
        </ul>
    </div>
</nav>

AarhusWebDevCoop/Views/Master.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = null;
}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Free Web tutorials">
    <meta name="keywords" content="HTML,CSS,XML,JavaScript">
    <meta name="author" content="John Doe">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Aarhus Web Dev Cooperation</title>
    
    <style>
        ul{ list-style: none; }
        html {  
            position: relative;
            min-height: 100%;
        }
        body {
            padding-bottom:280px;
        }
    </style>
    
  </head>
  <body>
    <header>
        
    </header>
     @Umbraco.RenderMacro("mainMenu")
     @RenderBody()
     @Html.Partial("sitemap")
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
 
    <script src="~/scripts/jquery-2.1.3.min.js"></script>
    <script src="~/scripts/bootstrap.min.js"></script>
    <script src="~/scripts/jquery.validate.min.js"></script>
    <script src="~/scripts/jquery.validate.unobtrusive.min.js"></script> 
 
  </body>
</html>

AarhusWebDevCoop/Views/Members.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.Members>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@using Umbraco.Core;
@using Umbraco.Core.Models;
@using Umbraco.Core.Services;
@using Newtonsoft.Json;
@using Umbraco.Web.Models;
@{
  Layout = "master.cshtml";
}

<div class="container pt-4 pb-4">
@{
    <h1>Active Members</h1>
    var memberService = ApplicationContext.Current.Services.MemberService;
    var members = memberService.GetMembersByMemberType("active");
    var prospects = memberService.GetMembersByMemberType("prospect");
    
    foreach (var member in members)
    {
        if (member.GetValue("photo") != null)
        {
            string image = member.GetValue<string>("photo");
            ImageCropDataSet imageCrops = JsonConvert.DeserializeObject<ImageCropDataSet>(image);
            string imagePath = imageCrops.Src.GetCropUrl(width: 100);
            <img src="@imagePath" /><br />
        }
        String[] skills = member.GetValue("skills").ToString().Split(',');
        string skillString = string.Join(", ", from skill in skills select umbraco.library.GetPreValueAsString(Convert.ToInt32(skill)));
        <p>
            <b>Name: </b> @member.Name<br />
            <b>Address: </b> @member.GetValue("address"), @member.GetValue("zip"), @member.GetValue("city") <br />
            <b>Email: </b> @member.Email<br />
            <b>Skills: </b> <span>@skillString</span> <br /><br />
        </p>
    }
}
</div>

AarhusWebDevCoop/Views/Message.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.Message>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = null;
}

AarhusWebDevCoop/Views/Partials/ContactForm.cshtml
@model AarhusWebDevCoop.ViewModels.ContactForm

@{
    Layout = null;
}

@if (TempData["success"] == null)
{

    using (Html.BeginUmbracoForm("HandleFormSubmit", "ContactFormSurface", new object { },
        new { @class = "form-horizontal" }))
    {
        <div>
            @Html.LabelFor(m => m.Name, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-6">
                @Html.TextBoxFor(m => m.Name, new { @class = "form-control", placeholder = "Name" })
                <div style="color: red">@Html.ValidationMessageFor(m => m.Name)</div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Email, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-6">
                @Html.TextBoxFor(m => m.Email, new { @class = "form-control", placeholder = "Email address" })
                <div style="color: red">@Html.ValidationMessageFor(m => m.Email)</div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Subject, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-6">
                @Html.TextBoxFor(m => m.Subject, new { @class = "form-control", placeholder = "Subject" })
                <div style="color: red">@Html.ValidationMessageFor(m => m.Subject)</div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Message, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-6">
                @Html.TextAreaFor(m => m.Message, new { @class = "form-control", placeholder = "Your Message", rows = "5" })
                <div style="color: red">@Html.ValidationMessageFor(m => m.Message)</div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-6">
                <button id="contact-submit" type="submit" class="btn btn-primary input-medium pull-left">
                    Send
                </button>
            </div>
        </div>
    }
}

else {
    <p>Thank you for contacting us. We’ll be in touch soon!</p>
}

AarhusWebDevCoop/Views/Partials/Grid/Bootstrap2-Fluid.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@* 
    Razor helpers located at the bottom of this file
*@

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true);
                    }
                </div>
            }   
        }else { 
            <div class="container-fluid">
                <div class="row-fluid clearfix">
                    @foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="@("span" + s.grid) column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>   
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @Umbraco.If(singleColumn, "<div class='container-fluid'>")
        <div class="row-fluid clearfix">
            @foreach ( var area in row.areas ) {
            <div class="@("span" + area.grid) column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
        @Umbraco.If(singleColumn, "</div>")
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties())
            {
                var propertyValue = HttpUtility.HtmlAttributeEncode(property.Value.ToString());
                attrs.Add(property.Name + "=\"" + propertyValue + "\"");
            }

        JObject style = contentItem.styles;

        if (style != null) {
            var cssVals = new List<string>();
            foreach (JProperty property in style.Properties())
            {
                var propertyValue = property.Value.ToString();
                if (string.IsNullOrWhiteSpace(propertyValue) == false)
                {
                    cssVals.Add(property.Name + ":" + propertyValue + ";");
                }
            }

            if (cssVals.Any())
                attrs.Add("style='" + HttpUtility.HtmlAttributeEncode(string.Join(" ", cssVals)) + "'");
        }

        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

AarhusWebDevCoop/Views/Partials/Grid/Bootstrap2.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true);
                    }
                </div>
            }   
        }else { 
            <div class="container">
                <div class="row clearfix">
                    @foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="@("span" + s.grid) column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>   
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @Umbraco.If(singleColumn, "<div class='container'>")
        <div class="row clearfix">
            @foreach ( var area in row.areas ) {
            <div class="@("span" + area.grid) column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
        @Umbraco.If(singleColumn, "</div>")
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties())
            {
                var propertyValue = HttpUtility.HtmlAttributeEncode(property.Value.ToString());
                attrs.Add(property.Name + "=\"" + propertyValue + "\"");
            }

        JObject style = contentItem.styles;

        if (style != null) {
            var cssVals = new List<string>();
            foreach (JProperty property in style.Properties())
            {
                var propertyValue = property.Value.ToString();
                if (string.IsNullOrWhiteSpace(propertyValue) == false)
                {
                    cssVals.Add(property.Name + ":" + propertyValue + ";");
                }
            }

            if (cssVals.Any())
                attrs.Add("style=\"" + HttpUtility.HtmlAttributeEncode(string.Join(" ", cssVals)) + "\"");
        }

        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

AarhusWebDevCoop/Views/Partials/Grid/Bootstrap3-Fluid.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@* 
    Razor helpers located at the bottom of this file
*@

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row);
                    }
                </div>
            }   
        }else { 
            <div class="row clearfix">
                @foreach (var s in Model.sections) {
                    <div class="grid-section">
                        <div class="col-md-@s.grid column">
                            @foreach (var row in s.rows) {
                                @renderRow(row);
                            }
                        </div>
                    </div>
                }
            </div>
        }
    </div>
}

@helper renderRow(dynamic row){
    <div @RenderElementAttributes(row)>
        <div class="row clearfix">
            @foreach ( var area in row.areas ) {
            <div class="col-md-@area.grid column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties())
            {
                var propertyValue = HttpUtility.HtmlAttributeEncode(property.Value.ToString());
                attrs.Add(property.Name + "=\"" + propertyValue + "\"");
            }

        JObject style = contentItem.styles;

        if (style != null) {
            var cssVals = new List<string>();
            foreach (JProperty property in style.Properties())
            {
                var propertyValue = property.Value.ToString();
                if (string.IsNullOrWhiteSpace(propertyValue) == false)
                {
                    cssVals.Add(property.Name + ":" + propertyValue + ";");
                }
            }

            if (cssVals.Any())
                attrs.Add("style='" + HttpUtility.HtmlAttributeEncode(string.Join(" ", cssVals)) + "'");
        }

        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

AarhusWebDevCoop/Views/Partials/Grid/Editors/Base.cshtml
@model dynamic
@using Umbraco.Web.Templates

@functions {
    public static string EditorView(dynamic contentItem)
    {
        string view = contentItem.editor.render != null ? contentItem.editor.render.ToString() : contentItem.editor.view.ToString();
        view = view.ToLower().Replace(".html", ".cshtml");
        
        if (!view.Contains("/")) {
            view = "grid/editors/" + view;
        }

        return view;
    }
}
@try
{
    string editor = EditorView(Model);                                                       
    <text>@Html.Partial(editor, (object)Model)</text>
}
catch (Exception ex) { 
<pre>@ex.ToString()</pre>
}

AarhusWebDevCoop/Views/Partials/Grid/Editors/Embed.cshtml
@model dynamic
@using Umbraco.Web.Templates


<div class="video-wrapper">
	@Html.Raw(Model.value)
</div>

AarhusWebDevCoop/Views/Partials/Grid/Editors/Macro.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates


@if (Model.value != null)
{
    string macroAlias = Model.value.macroAlias.ToString();
    ViewDataDictionary parameters = new ViewDataDictionary();
    foreach (dynamic mpd in Model.value.macroParamsDictionary)
    {
        parameters.Add(mpd.Name, mpd.Value);
    }

    <text>
        @Umbraco.RenderMacro(macroAlias, parameters)
    </text>
}

AarhusWebDevCoop/Views/Partials/Grid/Editors/Media.cshtml
@model dynamic
@using Umbraco.Web.Templates

@if (Model.value != null)
{   
    var url = Model.value.image;
    if(Model.editor.config != null && Model.editor.config.size != null){
        url += "?width=" + Model.editor.config.size.width;
        url += "&height=" + Model.editor.config.size.height;

        if(Model.value.focalPoint != null){
            url += "&center=" + Model.value.focalPoint.top +"," + Model.value.focalPoint.left;
            url += "&mode=crop";
        }
    }

    var altText = Model.value.altText ?? Model.value.caption ?? string.Empty;
    
    <img src="@url" alt="@altText">
    
    if (Model.value.caption != null)
    {
        <p class="caption">@Model.value.caption</p>
    }
}